import { PrismaClient } from '@prisma/client';
import {
  SETTINGS_BUY_SELL_FEE_PERCENTAGE,
  SETTINGS_GROUP_APPLICATION,
  SETTINGS_GROUP_EMAIL,
  SETTINGS_GROUP_HOMEPAGE,
  SETTINGS_GROUP_GENERAL,
  SETTINGS_GROUP_LOGO,
  SETTINGS_GROUP_SOCIAL,
  SETTINGS_KEY_MINTING_INTERVAL_DURATION_IN_MIN,
  SETTINGS_KEY_PER_DAY_MINTING_LIMIT,
  SETTINGS_MAX_INTERVAL_FOR_BUY_SELL_OFFER_IN_MIN,
  SETTINGS_MIN_INTERVAL_FOR_BUY_SELL_OFFER_IN_MIN,
  SETTINGS_SLUG_ADDRESS,
  SETTINGS_SLUG_ADMIN_COMMISSION,
  SETTINGS_SLUG_APPLICATION_TITLE,
  SETTINGS_SLUG_APP_LOGO_LARGE,
  SETTINGS_SLUG_APP_LOGO_SMALL,
  SETTINGS_SLUG_ASSET_DESCRIPTION,
  SETTINGS_SLUG_ASSET_TITLE,
  SETTINGS_SLUG_BANNER_DESCRIPTION,
  SETTINGS_SLUG_BANNER_IMAGE,
  SETTINGS_SLUG_BANNER_TITLE,
  SETTINGS_SLUG_CATEGORY_DESCRIPTION,
  SETTINGS_SLUG_CATEGORY_TITLE,
  SETTINGS_SLUG_CONTRACT_EMAIL,
  SETTINGS_SLUG_CONTRACT_PHONE,
  SETTINGS_SLUG_COPY_RIGHT,
  SETTINGS_SLUG_FACEBOOK_LINK,
  SETTINGS_SLUG_FAVICON_LOGO,
  SETTINGS_SLUG_DISCORD_LINK,
  SETTINGS_SLUG_INSTAGRAM_LINK,
  SETTINGS_SLUG_INSTRUCTION_ADD_NFTS,
  SETTINGS_SLUG_INSTRUCTION_CREATE_COLLECTION,
  SETTINGS_SLUG_INSTRUCTION_IMAGE,
  SETTINGS_SLUG_INSTRUCTION_LIST_FOR_SALE,
  SETTINGS_SLUG_INSTRUCTION_SECTION_DESCRIPTION,
  SETTINGS_SLUG_INSTRUCTION_SECTION_TITLE,
  SETTINGS_SLUG_INSTRUCTION_SETUP_WALLET,
  SETTINGS_SLUG_LINKEDIN_LINK,
  SETTINGS_SLUG_MAIL_DIRIVER,
  SETTINGS_SLUG_MAIL_ENCRYPTION,
  SETTINGS_SLUG_MAIL_FROM_ADDRESS,
  SETTINGS_SLUG_MAIL_FROM_NAME,
  SETTINGS_SLUG_MAIL_HOST,
  SETTINGS_SLUG_MAIL_PASSWORD,
  SETTINGS_SLUG_MAIL_PORT,
  SETTINGS_SLUG_MAIL_USERNAME,
  SETTINGS_SLUG_RESOURCE_SECTION_DESCRIPTION,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_TITLE,
  SETTINGS_SLUG_SELL_OFFER_DESCRIPTION,
  SETTINGS_SLUG_SELL_OFFER_TITLE,
  SETTINGS_SLUG_TWITTER_LINK,
  SETTINGS_SLUG_VIDEO_SECTION_DESCTIPTION,
  SETTINGS_SLUG_VIDEO_SECTION_TITLE,
  SETTINGS_SLUG_VIDEO_URL,
  SETTINGS_SLUG_WALLET_ADDRESS,
  SETTINGS_SLUG_WHATSAPP_LINK,
  SETTINGS_VALUE_TYPE_MEDIA_URL,
  SETTINGS_SLUG_TOP_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_TOP_COLLECTION_TITLE,
  SETTINGS_SLUG_FEATURED_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_FEATURED_COLLECTION_TITLE,
  SETTINGS_SLUG_TRENDING_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_TRENDING_COLLECTION_TITLE,
} from '../../src/app/helpers/slugconstants';

export async function settingsSeeder(prisma: PrismaClient) {
  await prisma.setting.createMany({
    data: [
      {
        option_group: SETTINGS_GROUP_APPLICATION,
        option_key: SETTINGS_KEY_MINTING_INTERVAL_DURATION_IN_MIN,
        option_value: '60',
      },
      {
        option_group: SETTINGS_GROUP_APPLICATION,
        option_key: SETTINGS_KEY_PER_DAY_MINTING_LIMIT,
        option_value: '2',
      },
      {
        option_group: SETTINGS_GROUP_APPLICATION,
        option_key: SETTINGS_BUY_SELL_FEE_PERCENTAGE,
        option_value: '2.5',
      },
      {
        option_group: SETTINGS_GROUP_APPLICATION,
        option_key: SETTINGS_MIN_INTERVAL_FOR_BUY_SELL_OFFER_IN_MIN,
        option_value: '30',
      },
      {
        option_group: SETTINGS_GROUP_APPLICATION,
        option_key: SETTINGS_MAX_INTERVAL_FOR_BUY_SELL_OFFER_IN_MIN,
        option_value: '260000',
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_APPLICATION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_APPLICATION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_CONTRACT_EMAIL,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_CONTRACT_PHONE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_ADDRESS,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_COPY_RIGHT,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_WALLET_ADDRESS,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_GENERAL,
        option_key: SETTINGS_SLUG_ADMIN_COMMISSION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_DIRIVER,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_HOST,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_PORT,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_USERNAME,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_PASSWORD,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_ENCRYPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_FROM_ADDRESS,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_EMAIL,
        option_key: SETTINGS_SLUG_MAIL_FROM_NAME,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_LOGO,
        option_key: SETTINGS_SLUG_APP_LOGO_LARGE,
        option_value: 'images/tests/codexpro.png',
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_LOGO,
        option_key: SETTINGS_SLUG_APP_LOGO_SMALL,
        option_value: 'images/tests/codexpro.png',
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_LOGO,
        option_key: SETTINGS_SLUG_FAVICON_LOGO,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_FACEBOOK_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_TWITTER_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_INSTAGRAM_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_DISCORD_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_WHATSAPP_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_SOCIAL,
        option_key: SETTINGS_SLUG_LINKEDIN_LINK,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_BANNER_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_BANNER_DESCRIPTION,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_BANNER_IMAGE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_CATEGORY_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_CATEGORY_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_TOP_COLLECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_TOP_COLLECTION_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_TRENDING_COLLECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_TRENDING_COLLECTION_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_FEATURED_COLLECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_FEATURED_COLLECTION_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_ASSET_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_ASSET_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_ONE_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_ONE_LINK,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_ONE_IMAGE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_TWO_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_TWO_LINK,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_TWO_IMAGE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_THREE_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_THREE_LINK,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_RESOURCE_SECTION_THREE_IMAGE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_SECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_SECTION_DESCRIPTION,
        option_value: null,
      },
      {
        value_type: SETTINGS_VALUE_TYPE_MEDIA_URL,
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_IMAGE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_SETUP_WALLET,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_CREATE_COLLECTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_ADD_NFTS,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_INSTRUCTION_LIST_FOR_SALE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_SELL_OFFER_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_SELL_OFFER_DESCRIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_VIDEO_SECTION_TITLE,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_VIDEO_SECTION_DESCTIPTION,
        option_value: null,
      },
      {
        option_group: SETTINGS_GROUP_HOMEPAGE,
        option_key: SETTINGS_SLUG_VIDEO_URL,
        option_value: null,
      },
    ],
    skipDuplicates: true,
  });
}
