import { Field, InputType } from '@nestjs/graphql';
import { FileUpload, GraphQLUpload } from 'graphql-upload';
import {
  SETTINGS_SLUG_BANNER_TITLE,
  SETTINGS_SLUG_CATEGORY_TITLE,
  SETTINGS_SLUG_BANNER_DESCRIPTION,
  SETTINGS_SLUG_CATEGORY_DESCRIPTION,
  SETTINGS_SLUG_ASSET_DESCRIPTION,
  SETTINGS_SLUG_ASSET_TITLE,
  SETTINGS_SLUG_INSTRUCTION_SECTION_DESCRIPTION,
  SETTINGS_SLUG_INSTRUCTION_SECTION_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_DESCRIPTION,
  SETTINGS_SLUG_RESOURCE_SECTION_TITLE,
  SETTINGS_SLUG_BANNER_IMAGE,
  SETTINGS_SLUG_INSTRUCTION_IMAGE,
  SETTINGS_SLUG_INSTRUCTION_ADD_NFTS,
  SETTINGS_SLUG_INSTRUCTION_CREATE_COLLECTION,
  SETTINGS_SLUG_INSTRUCTION_LIST_FOR_SALE,
  SETTINGS_SLUG_INSTRUCTION_SETUP_WALLET,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_TITLE,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_IMAGE,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_LINK,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_TITLE,
  SETTINGS_SLUG_SELL_OFFER_DESCRIPTION,
  SETTINGS_SLUG_SELL_OFFER_TITLE,
  SETTINGS_SLUG_VIDEO_SECTION_DESCTIPTION,
  SETTINGS_SLUG_VIDEO_SECTION_TITLE,
  SETTINGS_SLUG_VIDEO_URL,
  SETTINGS_SLUG_RESOURCE_SECTION_ONE_DESCRIPTION,
  SETTINGS_SLUG_RESOURCE_SECTION_TWO_DESCRIPTION,
  SETTINGS_SLUG_RESOURCE_SECTION_THREE_DESCRIPTION,
  SETTINGS_SLUG_TOP_COLLECTION_TITLE,
  SETTINGS_SLUG_TOP_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_TRENDING_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_TRENDING_COLLECTION_TITLE,
  SETTINGS_SLUG_FEATURED_COLLECTION_DESCRIPTION,
  SETTINGS_SLUG_FEATURED_COLLECTION_TITLE,
} from 'src/app/helpers/slugconstants';

@InputType()
export class HomepageSettingsInput {
  @Field({ nullable: true })
  [SETTINGS_SLUG_BANNER_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_BANNER_DESCRIPTION]: string;

  @Field(() => GraphQLUpload, { nullable: true })
  [SETTINGS_SLUG_BANNER_IMAGE]: FileUpload;

  @Field({ nullable: true })
  [SETTINGS_SLUG_CATEGORY_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_CATEGORY_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_TOP_COLLECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_TOP_COLLECTION_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_TRENDING_COLLECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_TRENDING_COLLECTION_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_FEATURED_COLLECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_FEATURED_COLLECTION_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_ASSET_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_ASSET_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_SECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_SECTION_DESCRIPTION]: string;

  @Field(() => GraphQLUpload, { nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_IMAGE]: FileUpload;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_SETUP_WALLET]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_CREATE_COLLECTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_ADD_NFTS]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_INSTRUCTION_LIST_FOR_SALE]: string;

  @Field(() => GraphQLUpload, { nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_ONE_IMAGE]: FileUpload;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_ONE_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_ONE_LINK]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_ONE_DESCRIPTION]: string;

  @Field(() => GraphQLUpload, { nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_TWO_IMAGE]: FileUpload;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_TWO_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_TWO_LINK]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_TWO_DESCRIPTION]: string;

  @Field(() => GraphQLUpload, { nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_THREE_IMAGE]: FileUpload;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_THREE_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_THREE_LINK]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_RESOURCE_SECTION_THREE_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_SELL_OFFER_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_SELL_OFFER_DESCRIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_VIDEO_SECTION_TITLE]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_VIDEO_SECTION_DESCTIPTION]: string;

  @Field({ nullable: true })
  [SETTINGS_SLUG_VIDEO_URL]: string;
}
